import { useState, useEffect } from 'react';
import { Download, RefreshCw, X, Printer } from 'lucide-react';
import { reportsAPI } from '../api/client';
import html2pdf from 'html2pdf.js';

interface Report {
  id: string;
  equipment_id: string;
  equipment_name: string;
  title: string;
  status: 'critical' | 'warning' | 'normal';
  findings: string;
  content: any;
  date: string;
}

export default function ReportsView() {
  const [reports, setReports] = useState<Report[]>([]);
  const [selectedReport, setSelectedReport] = useState<Report | null>(null);
  const [loading, setLoading] = useState(true);
  const [equipmentFilter, setEquipmentFilter] = useState<string>('All Equipment');

  useEffect(() => {
    loadReports();
    const interval = setInterval(loadReports, 30000);
    return () => clearInterval(interval);
  }, []);

  const loadReports = async () => {
    try {
      const response = await reportsAPI.getReports(undefined, 30);
      setReports(response.data.reports || []);
    } catch (error) {
      console.error('Failed to load reports:', error);
    } finally {
      setLoading(false);
    }
  };

  const getRiskColor = (status: string) => {
    const colors = {
      critical: '#ef4444',
      warning: '#f97316',
      normal: '#22c55e'
    };
    return colors[status as keyof typeof colors] || colors.normal;
  };

  const downloadReportAsPDF = (report: Report) => {
    // Extract content properly
    let content = '';
    if (report.content && report.content.report_content) {
      content = report.content.report_content;
    } else if (typeof report.content === 'string') {
      content = report.content;
    } else {
      content = JSON.stringify(report.content, null, 2);
    }
    
    // Clean up escaped characters
    content = content
      .replace(/\\n\\n/g, '\n\n')
      .replace(/\\n/g, '\n')
      .replace(/\\"/g, '"')
      .replace(/\\t/g, '  ');
    
    const htmlContent = `
      <div style="font-family: 'Segoe UI', Arial, sans-serif; padding: 40px; max-width: 800px; margin: 0 auto; color: #1a1a1a;">
        <div style="border-bottom: 3px solid #0ea5e9; padding-bottom: 20px; margin-bottom: 30px;">
          <h1 style="color: #1a1a1a; margin: 0; font-size: 28px;">Alloy Agent - Maintenance Report</h1>
        </div>
        
        <div style="background: #f8f9fa; padding: 20px; border-radius: 8px; margin-bottom: 30px;">
          <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 15px;">
            <div>
              <p style="margin: 8px 0; font-size: 14px;"><strong>Equipment:</strong> ${report.equipment_name}</p>
              <p style="margin: 8px 0; font-size: 14px;"><strong>Equipment ID:</strong> ${report.equipment_id}</p>
              <p style="margin: 8px 0; font-size: 14px;"><strong>Date:</strong> ${new Date(report.date).toLocaleString()}</p>
            </div>
            <div style="text-align: right;">
              <p style="margin: 8px 0; font-size: 14px;"><strong>Status:</strong> <span style="color: ${getRiskColor(report.status)}; font-weight: bold; font-size: 16px;">${report.status.toUpperCase()}</span></p>
              <p style="margin: 8px 0; font-size: 14px;"><strong>Report ID:</strong> ${report.id}</p>
            </div>
          </div>
        </div>
        
        <div style="line-height: 1.8; color: #333; font-size: 13px;">
          ${markdownToHTML(content)}
        </div>
        
        <hr style="border: none; border-top: 1px solid #e5e7eb; margin: 40px 0 20px 0;">
        
        <div style="text-align: center; color: #666; font-size: 11px;">
          <p style="margin: 5px 0;">Generated by Alloy Agent AI-Powered Maintenance System</p>
          <p style="margin: 5px 0;">Report generated on ${new Date().toLocaleString()}</p>
        </div>
      </div>
    `;

    const opt = {
      margin: 10 as number,
      filename: `report-${report.equipment_id}-${new Date().toISOString().split('T')[0]}.pdf`,
      image: { type: 'jpeg', quality: 0.98 },
      html2canvas: { scale: 2, useCORS: true, logging: false },
      jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' }
    } as any;

    html2pdf().set(opt).from(htmlContent).save();
  };

  const exportAllReports = () => {
    const markdown = reports.map(r => `# ${r.title}\n\n${typeof r.content === 'string' ? r.content : JSON.stringify(r.content, null, 2)}\n\n---\n\n`).join('');
    const blob = new Blob([markdown], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `all-reports-${new Date().toISOString().split('T')[0]}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const printReport = (report: Report) => {
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;

    const content = typeof report.content === 'string' ? report.content : JSON.stringify(report.content, null, 2);
    
    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
      <head>
        <title>${report.title}</title>
        <style>
          @media print {
            body { margin: 0; padding: 20px; }
            .no-print { display: none; }
          }
          body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
          }
          h1 { color: #1a1a1a; border-bottom: 3px solid #0ea5e9; padding-bottom: 10px; }
          h2 { color: #0ea5e9; margin-top: 20px; }
          h3 { color: #0284c7; }
          .header { display: flex; justify-content: space-between; margin-bottom: 20px; }
          .status-critical { color: #ef4444; font-weight: bold; }
          .status-warning { color: #f97316; font-weight: bold; }
          .status-normal { color: #22c55e; font-weight: bold; }
          pre { background: #f5f5f5; padding: 10px; border-radius: 4px; overflow-x: auto; }
          code { background: #f5f5f5; padding: 2px 6px; border-radius: 3px; }
          ul, ol { margin-left: 20px; }
          .print-button { margin-bottom: 20px; padding: 10px 20px; background: #0ea5e9; color: white; border: none; cursor: pointer; }
        </style>
      </head>
      <body>
        <button class="print-button no-print" onclick="window.print()">🖨️ Print Report</button>
        <div class="header">
          <div>
            <h1>Alloy Agent - Maintenance Report</h1>
            <p><strong>Equipment:</strong> ${report.equipment_name} (${report.equipment_id})</p>
            <p><strong>Date:</strong> ${new Date(report.date).toLocaleString()}</p>
          </div>
          <div>
            <p><strong>Status:</strong> <span class="status-${report.status}">${report.status.toUpperCase()}</span></p>
            <p><strong>Report ID:</strong> ${report.id}</p>
          </div>
        </div>
        <hr>
        <div>${markdownToHTML(content)}</div>
        <hr>
        <footer style="margin-top: 30px; text-align: center; color: #666; font-size: 12px;">
          <p>Generated by Alloy Agent AI-Powered Maintenance System</p>
          <p>Report generated on ${new Date().toLocaleString()}</p>
        </footer>
      </body>
      </html>
    `);
    printWindow.document.close();
  };

  const markdownToHTML = (markdown: string): string => {
    return markdown
      .replace(/^### (.*$)/gim, '<h3>$1</h3>')
      .replace(/^## (.*$)/gim, '<h2>$1</h2>')
      .replace(/^# (.*$)/gim, '<h1>$1</h1>')
      .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
      .replace(/\*(.*?)\*/g, '<em>$1</em>')
      .replace(/^- (.*$)/gim, '<li>$1</li>')
      .replace(/^([0-9]+)\. (.*$)/gim, '<li>$2</li>')
      .replace(/(<li>.*<\/li>)/s, '<ul>$1</ul>')
      .replace(/`([^`]+)`/g, '<code>$1</code>')
      .replace(/```([^```]+)```/g, '<pre><code>$1</code></pre>')
      .replace(/\n\n/g, '<br><br>')
      .replace(/\n/g, '<br>');
  };

  const filteredReports = equipmentFilter === 'All Equipment' 
    ? reports 
    : reports.filter(r => r.equipment_id === equipmentFilter);

  const uniqueEquipment = ['All Equipment', ...new Set(reports.map(r => r.equipment_id))];

  return (
    <div className="flex h-full">
      {/* Reports List */}
      <div className="flex-1 flex flex-col">
        <div className="flex items-center justify-between mb-4">
          <h2 className="text-xs font-mono tracking-widest" style={{ color: 'var(--accent-cyan)' }}>
            📊 ANALYSIS REPORTS
          </h2>
          <div className="flex items-center space-x-2">
            <button
              onClick={exportAllReports}
              disabled={reports.length === 0}
              className="px-3 py-1 text-xs font-mono rounded-sm transition-all disabled:opacity-50"
              style={{
                backgroundColor: 'var(--bg-elevated)',
                border: '1px solid var(--border-default)',
                color: 'var(--accent-cyan)'
              }}
            >
              <Download className="w-3 h-3 inline mr-1" />
              EXPORT ALL
            </button>
            <button
              onClick={loadReports}
              disabled={loading}
              className="p-1.5 rounded-sm transition-all"
              style={{
                backgroundColor: 'var(--bg-elevated)',
                border: '1px solid var(--border-default)',
                color: 'var(--accent-cyan)'
              }}
            >
              <RefreshCw className={`w-3 h-3 ${loading ? 'animate-spin' : ''}`} />
            </button>
          </div>
        </div>

        {/* Filter */}
        <div className="mb-3">
          <select
            value={equipmentFilter}
            onChange={(e) => setEquipmentFilter(e.target.value)}
            className="w-full px-3 py-2 text-xs font-mono rounded-sm"
            style={{
              backgroundColor: 'var(--bg-elevated)',
              border: '1px solid var(--border-default)',
              color: 'var(--text-primary)'
            }}
          >
            {uniqueEquipment.map(eq => (
              <option key={eq} value={eq}>{eq}</option>
            ))}
          </select>
        </div>

        <div className="text-xs font-mono mb-3" style={{ color: 'var(--text-tertiary)' }}>
          {filteredReports.length} entries
        </div>

        {/* Reports List */}
        <div className="flex-1 overflow-y-auto space-y-2">
          {loading ? (
            <div className="text-center py-12">
              <p className="text-xs font-mono" style={{ color: 'var(--text-secondary)' }}>Loading...</p>
            </div>
          ) : filteredReports.length === 0 ? (
            <div className="text-center py-12 rounded-sm" style={{ backgroundColor: 'var(--bg-surface)', border: '1px solid var(--border-default)' }}>
              <p className="text-sm font-mono" style={{ color: 'var(--text-secondary)' }}>No reports yet</p>
              <p className="text-xs font-sans mt-1" style={{ color: 'var(--text-tertiary)' }}>Reports auto-generate when anomalies detected</p>
            </div>
          ) : (
            filteredReports.map(report => (
              <div
                key={report.id}
                onClick={() => setSelectedReport(report)}
                className="p-3 rounded-sm cursor-pointer transition-all hover:border-opacity-70"
                style={{
                  backgroundColor: selectedReport?.id === report.id ? 'var(--bg-elevated)' : 'var(--bg-surface)',
                  border: `1px solid ${selectedReport?.id === report.id ? 'var(--accent-cyan)' : 'var(--border-default)'}`
                }}
              >
                <div className="flex items-start justify-between mb-2">
                  <div className="flex-1">
                    <div className="text-sm font-sans mb-1" style={{ color: 'var(--text-primary)' }}>
                      {report.equipment_name || report.equipment_id}
                    </div>
                    <div className="text-xs font-sans" style={{ color: 'var(--text-secondary)' }}>
                      {report.findings}
                    </div>
                  </div>
                  <span
                    className="px-2 py-0.5 rounded-sm text-2xs font-mono uppercase"
                    style={{
                      backgroundColor: `${getRiskColor(report.status)}20`,
                      color: getRiskColor(report.status)
                    }}
                  >
                    {report.status}
                  </span>
                </div>
                <div className="text-2xs font-mono" style={{ color: 'var(--text-tertiary)' }}>
                  {new Date(report.date).toLocaleString()}
                </div>
              </div>
            ))
          )}
        </div>
      </div>

      {/* Report Detail Panel */}
      {selectedReport && (
        <div 
          className="w-2/3 ml-4 flex flex-col rounded-sm overflow-hidden"
          style={{ backgroundColor: 'var(--bg-surface)', border: '1px solid var(--border-default)' }}
        >
          {/* Header */}
          <div className="p-4 border-b flex items-start justify-between" style={{ borderColor: 'var(--border-default)' }}>
            <div className="flex-1">
              <div className="text-lg font-sans mb-1" style={{ color: 'var(--text-primary)' }}>
                {selectedReport.title}
              </div>
              <div className="flex items-center space-x-3 text-xs font-mono" style={{ color: 'var(--text-tertiary)' }}>
                <span>Equipment ID: {selectedReport.equipment_id}</span>
                <span>•</span>
                <span>Incident ID: {selectedReport.id}</span>
              </div>
              <div className="text-xs font-mono mt-1" style={{ color: 'var(--text-tertiary)' }}>
                Generated: {new Date(selectedReport.date).toLocaleString('en-US', { 
                  month: 'short', 
                  day: 'numeric', 
                  year: 'numeric', 
                  hour: '2-digit', 
                  minute: '2-digit' 
                })}
              </div>
            </div>
            <div className="flex items-center space-x-2">
              <button
                onClick={() => printReport(selectedReport)}
                className="p-1.5 rounded-sm hover:bg-gray-100"
                style={{ color: 'var(--text-secondary)' }}
                title="Print Report"
              >
                <Printer className="w-4 h-4" />
              </button>
              <button
                onClick={() => setSelectedReport(null)}
                className="p-1 rounded-sm"
                style={{ color: 'var(--text-secondary)' }}
              >
                <X className="w-4 h-4" />
              </button>
            </div>
          </div>

          {/* Content */}
          <div className="flex-1 overflow-y-auto p-6">
            {/* Show ONLY Full Detailed Report if available, otherwise show structured sections */}
            {selectedReport.content?.report_content ? (
              /* Full Comprehensive Report - Clean Preview Mode */
              <div>
                <div className="flex items-center justify-between mb-4">
                  <div className="text-lg font-mono uppercase flex items-center" style={{ color: 'var(--accent-cyan)' }}>
                    <span className="mr-2">📄</span> Equipment Health Analysis Report
                  </div>
                  <button
                    onClick={() => selectedReport && downloadReportAsPDF(selectedReport)}
                    className="px-4 py-2 text-xs font-mono rounded-sm hover:opacity-80 transition-all flex items-center space-x-2"
                    style={{
                      backgroundColor: 'var(--accent-cyan)',
                      color: '#0a0e27'
                    }}
                  >
                    <Download className="w-4 h-4" />
                    <span>DOWNLOAD AS PDF</span>
                  </button>
                </div>
                
                {/* Clean Report Preview */}
                <div 
                  className="report-content p-6 rounded-sm"
                  style={{ 
                    backgroundColor: 'var(--bg-elevated)',
                    border: '1px solid var(--border-default)',
                    color: 'var(--text-primary)',
                    lineHeight: '1.8',
                    fontSize: '14px'
                  }}
                >
                  <style>{`
                    .report-content h1 {
                      font-size: 24px;
                      font-weight: bold;
                      color: var(--accent-cyan);
                      margin-top: 24px;
                      margin-bottom: 16px;
                      padding-bottom: 8px;
                      border-bottom: 2px solid var(--border-default);
                    }
                    .report-content h2 {
                      font-size: 18px;
                      font-weight: 600;
                      color: var(--accent-cyan);
                      margin-top: 20px;
                      margin-bottom: 12px;
                    }
                    .report-content h3 {
                      font-size: 16px;
                      font-weight: 600;
                      color: var(--text-primary);
                      margin-top: 16px;
                      margin-bottom: 8px;
                    }
                    .report-content p {
                      margin-bottom: 12px;
                    }
                    .report-content ul, .report-content ol {
                      margin-left: 24px;
                      margin-bottom: 12px;
                    }
                    .report-content li {
                      margin-bottom: 6px;
                    }
                    .report-content strong {
                      font-weight: 600;
                      color: var(--text-primary);
                    }
                    .report-content em {
                      font-style: italic;
                    }
                    .report-content code {
                      background: var(--bg-surface);
                      padding: 2px 6px;
                      border-radius: 3px;
                      font-family: monospace;
                      font-size: 13px;
                    }
                    .report-content table {
                      width: 100%;
                      border-collapse: collapse;
                      margin: 16px 0;
                    }
                    .report-content th, .report-content td {
                      border: 1px solid var(--border-default);
                      padding: 8px 12px;
                      text-align: left;
                    }
                    .report-content th {
                      background: var(--bg-surface);
                      font-weight: 600;
                    }
                    .report-content hr {
                      border: none;
                      border-top: 1px solid var(--border-default);
                      margin: 20px 0;
                    }
                  `}</style>
                  <div dangerouslySetInnerHTML={{ __html: markdownToHTML(selectedReport.content.report_content) }} />
                </div>
              </div>
            ) : (
              /* Fallback: Show structured sections if full report not available */
              <div className="space-y-6">
            {/* Risk Level Banner */}
            <div className="p-4 rounded-sm" style={{ 
              backgroundColor: `${getRiskColor(selectedReport.status)}15`,
              border: `2px solid ${getRiskColor(selectedReport.status)}40`
            }}>
              <div className="flex items-center justify-between">
                <div>
                  <div className="text-xs font-mono uppercase mb-1" style={{ color: 'var(--text-tertiary)' }}>
                    Risk Level
                  </div>
                  <span
                    className="text-lg font-mono uppercase font-bold"
                    style={{ color: getRiskColor(selectedReport.status) }}
                  >
                    {selectedReport.status}
                  </span>
                </div>
                {selectedReport.content?.risk_level && (
                  <div className="text-right">
                    <div className="text-xs font-mono" style={{ color: 'var(--text-tertiary)' }}>
                      Confidence
                    </div>
                    <div className="text-sm font-mono font-bold" style={{ color: 'var(--text-primary)' }}>
                      HIGH
                    </div>
                  </div>
                )}
              </div>
            </div>

            {/* Summary */}
            <div>
              <div className="text-sm font-mono uppercase mb-2 flex items-center" style={{ color: 'var(--accent-cyan)' }}>
                <span className="mr-2">⚠️</span> Fault Description
              </div>
              <div className="p-3 rounded-sm text-sm font-sans leading-relaxed" style={{ 
                backgroundColor: 'var(--bg-elevated)',
                color: 'var(--text-primary)',
                border: '1px solid var(--border-subtle)'
              }}>
                {selectedReport.findings || 'No description available'}
              </div>
            </div>

            {/* Root Causes */}
            {(selectedReport.content?.root_causes && selectedReport.content.root_causes.length > 0) ? (
              <div>
                <div className="text-sm font-mono uppercase mb-3 flex items-center" style={{ color: 'var(--accent-cyan)' }}>
                  <span className="mr-2">🔍</span> Root Cause Analysis
                </div>
                <div className="space-y-3">
                  {selectedReport.content.root_causes.map((cause: any, i: number) => (
                    <div key={i} className="p-3 rounded-sm" style={{ 
                      backgroundColor: 'var(--bg-elevated)',
                      borderLeft: `3px solid ${getRiskColor(selectedReport.status)}`
                    }}>
                      <div className="flex items-start justify-between mb-2">
                        <div className="text-sm font-sans font-medium" style={{ color: 'var(--text-primary)' }}>
                          {i + 1}. {cause.cause}
                        </div>
                        {cause.confidence && (
                          <span className="text-xs font-mono px-2 py-0.5 rounded-sm" style={{
                            backgroundColor: 'var(--bg-surface)',
                            color: 'var(--accent-cyan)'
                          }}>
                            {Math.round((cause.confidence || 0) * 100)}% confident
                          </span>
                        )}
                      </div>
                      {cause.evidence && (
                        <div className="text-xs font-sans mt-1" style={{ color: 'var(--text-secondary)' }}>
                          Evidence: {cause.evidence}
                        </div>
                      )}
                    </div>
                  ))}
                </div>
              </div>
            ) : (
              <div>
                <div className="text-sm font-mono uppercase mb-3 flex items-center" style={{ color: 'var(--accent-cyan)' }}>
                  <span className="mr-2">🔍</span> Analysis
                </div>
                <div className="p-3 rounded-sm text-sm font-sans leading-relaxed" style={{ 
                  backgroundColor: 'var(--bg-elevated)',
                  color: 'var(--text-primary)',
                  border: '1px solid var(--border-subtle)'
                }}>
                  {typeof selectedReport.content === 'string' 
                    ? selectedReport.content 
                    : selectedReport.content?.summary || 'Analysis in progress...'}
                </div>
              </div>
            )}

            {/* Recommendations */}
            {selectedReport.content?.recommendations && selectedReport.content.recommendations.length > 0 && (
              <div>
                <div className="text-sm font-mono uppercase mb-3 flex items-center" style={{ color: 'var(--accent-cyan)' }}>
                  <span className="mr-2">🔧</span> Maintenance Actions Required
                </div>
                <div className="space-y-2">
                  {selectedReport.content.recommendations.map((rec: any, i: number) => (
                    <div key={i} className="p-3 rounded-sm flex items-start space-x-3" style={{ 
                      backgroundColor: 'var(--bg-elevated)',
                      border: '1px solid var(--border-default)'
                    }}>
                      <div className="flex-shrink-0 w-6 h-6 rounded-full flex items-center justify-center text-xs font-mono font-bold" style={{
                        backgroundColor: rec.priority === 'CRITICAL' || rec.priority === 'HIGH' ? `${getRiskColor('critical')}30` : 'var(--bg-surface)',
                        color: rec.priority === 'CRITICAL' || rec.priority === 'HIGH' ? getRiskColor('critical') : 'var(--accent-cyan)'
                      }}>
                        {i + 1}
                      </div>
                      <div className="flex-1">
                        <div className="text-sm font-sans font-medium mb-1" style={{ color: 'var(--text-primary)' }}>
                          {rec.action}
                        </div>
                        <div className="flex items-center space-x-3 text-xs font-mono" style={{ color: 'var(--text-tertiary)' }}>
                          {rec.estimated_time && (
                            <span>⏱️ {rec.estimated_time}</span>
                          )}
                          {rec.required_parts && rec.required_parts.length > 0 && (
                            <span>🔩 {rec.required_parts.join(', ')}</span>
                          )}
                        </div>
                        {rec.safety_notes && (
                          <div className="mt-2 text-xs font-sans p-2 rounded-sm" style={{
                            backgroundColor: '#fef3c7',
                            color: '#92400e',
                            border: '1px solid #fde68a'
                          }}>
                            ⚠️ Safety: {rec.safety_notes}
                          </div>
                        )}
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Sensor Data */}
            {selectedReport.content?.sensor_readings && (
              <div>
                <div className="text-sm font-mono uppercase mb-3 flex items-center" style={{ color: 'var(--accent-cyan)' }}>
                  <span className="mr-2">📊</span> Sensor Readings at Time of Detection
                </div>
                <div className="grid grid-cols-2 gap-2">
                  {Object.entries(selectedReport.content.sensor_readings).map(([key, value]: [string, any]) => (
                    <div key={key} className="p-2 rounded-sm" style={{ 
                      backgroundColor: 'var(--bg-elevated)',
                      border: '1px solid var(--border-default)'
                    }}>
                      <div className="text-xs font-mono uppercase" style={{ color: 'var(--text-tertiary)' }}>
                        {key.replace('_', ' ')}
                      </div>
                      <div className="text-sm font-mono font-bold" style={{ color: 'var(--text-primary)' }}>
                        {typeof value === 'number' ? value.toFixed(2) : value}
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Anomalies Detected */}
            {selectedReport.content?.anomalies && selectedReport.content.anomalies.length > 0 && (
              <div>
                <div className="text-sm font-mono uppercase mb-3 flex items-center" style={{ color: 'var(--accent-cyan)' }}>
                  <span className="mr-2">🚨</span> Anomalies Detected
                </div>
                <div className="space-y-2">
                  {selectedReport.content.anomalies.map((anomaly: any, i: number) => (
                    <div key={i} className="p-2 rounded-sm text-xs font-mono" style={{ 
                      backgroundColor: 'var(--bg-elevated)',
                      color: 'var(--text-secondary)',
                      border: '1px solid var(--border-default)'
                    }}>
                      {anomaly.message || `${anomaly.sensor}: ${anomaly.value} (threshold: ${anomaly.threshold})`}
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* System Metadata */}
            <div className="pt-4 border-t" style={{ borderColor: 'var(--border-subtle)' }}>
              <div className="text-xs font-mono uppercase mb-2" style={{ color: 'var(--text-tertiary)' }}>
                System Information
              </div>
              <div className="grid grid-cols-2 gap-2 text-xs font-mono" style={{ color: 'var(--text-secondary)' }}>
                {selectedReport.content?.agents_used && (
                  <div>
                    <span style={{ color: 'var(--text-tertiary)' }}>Agents Used:</span>{' '}
                    {selectedReport.content.agents_used.join(', ')}
                  </div>
                )}
                {selectedReport.content?.incident_id && (
                  <div>
                    <span style={{ color: 'var(--text-tertiary)' }}>Incident ID:</span>{' '}
                    {selectedReport.content.incident_id}
                  </div>
                )}
                <div>
                  <span style={{ color: 'var(--text-tertiary)' }}>Report ID:</span>{' '}
                  {selectedReport.id}
                </div>
                <div>
                  <span style={{ color: 'var(--text-tertiary)' }}>Equipment Type:</span>{' '}
                  {selectedReport.content?.equipment_type || 'Unknown'}
                </div>
              </div>
            </div>
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
}
